"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { formatCurrency } from "@/lib/finance";
import { Icon } from "./icons";
import styles from "./provider-portal.module.css";
interface Site{id:string;name:string;city:string} interface Row{entry_date:string;provider_amount:number|string;entry_type:string;description:string|null}
const num=(v:number|string)=>Number(v)||0;const mk=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;
export function ProviderRevenue(){const supabase=useMemo(()=>createClient(),[]);const[uid,setUid]=useState("");const[sites,setSites]=useState<Site[]>([]);const[siteId,setSiteId]=useState("");const[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
const load=useCallback(async(sid:string,id:string,m:Date)=>{const start=`${mk(m)}-01`;const n=new Date(m.getFullYear(),m.getMonth()+1,1);const end=`${mk(n)}-01`;const{data,error:e}=await supabase.from("financial_entries").select("entry_date,provider_amount,entry_type,description").eq("provider_id",id).eq("concession_id",sid).gte("entry_date",start).lt("entry_date",end).order("entry_date");if(e)setError(e.message);else setRows((data??[]) as Row[])},[supabase]);
useEffect(()=>{(async()=>{const{data:{user}}=await supabase.auth.getUser();if(!user){setLoading(false);return}const{data:a}=await supabase.from("concession_access").select("concession_id").eq("profile_id",user.id);const ids=(a??[]).map(x=>x.concession_id as string);const{data:s}=ids.length?await supabase.from("concessions").select("id,name,city").in("id",ids).eq("active",true).is("archived_at",null):{data:[]};const list=(s??[]) as Site[];const first=list[0]?.id??"";setUid(user.id);setSites(list);setSiteId(first);if(first)await load(first,user.id,month);setLoading(false)})()},[load,month,supabase]);
const daily=useMemo(()=>{const m=new Map<string,number>();for(const r of rows)m.set(r.entry_date,(m.get(r.entry_date)??0)+num(r.provider_amount));return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[rows]);const total=rows.reduce((s,r)=>s+num(r.provider_amount),0);const today=new Date().toISOString().slice(0,10);const todayAmount=daily.find(x=>x[0]===today)?.[1]??0;const avg=daily.length?total/daily.length:0;const max=Math.max(1,...daily.map(x=>x[1]));const move=async(n:number)=>{const m=new Date(month.getFullYear(),month.getMonth()+n,1);setMonth(m);setLoading(true);await load(siteId,uid,m);setLoading(false)};if(loading)return <div className={styles.panel}><div className={styles.empty}>Chargement des revenus…</div></div>;
return <div className={styles.page}><div className={styles.calendarToolbar}><div><span className={styles.eyebrow}>Suivi personnel</span><h1 className={styles.heroTitle}>Mes revenus</h1><p className={styles.muted}>Consulte ton chiffre d’affaires jour par jour et le total du mois.</p></div>{sites.length>1&&<select className={styles.siteSelect} value={siteId} onChange={async e=>{setSiteId(e.target.value);await load(e.target.value,uid,month)}}>{sites.map(s=><option key={s.id} value={s.id}>{s.name} · {s.city}</option>)}</select>}</div>{error&&<div className={styles.alert}>{error}</div>}<section className={styles.revenueCards}><article className={styles.revenueCard}><small>Aujourd’hui</small><strong>{formatCurrency(todayAmount)}</strong></article><article className={styles.revenueCard}><small>Ce mois</small><strong>{formatCurrency(total)}</strong></article><article className={styles.revenueCard}><small>Moyenne par jour rémunéré</small><strong>{formatCurrency(avg)}</strong></article></section><article className={styles.panel}><div className={styles.panelHead}><h2>{month.toLocaleDateString("fr-FR",{month:"long",year:"numeric"})}</h2><div className={styles.calendarNav}><button className={styles.secondary} onClick={()=>void move(-1)}><Icon name="chevronLeft"/></button><button className={styles.secondary} onClick={()=>void move(1)}><Icon name="chevronRight"/></button></div></div><div className={styles.chart}>{daily.length?daily.map(([date,value])=><div className={styles.barWrap} key={date} title={`${date} : ${formatCurrency(value)}`}><div className={styles.bar} style={{height:`${Math.max(3,(value/max)*175)}px`}}/><small>{new Date(`${date}T12:00:00`).getDate()}</small></div>):<div className={styles.empty}>Aucun revenu enregistré pour ce mois.</div>}</div></article><article className={styles.panel}><div className={styles.panelHead}><h2>Détail journalier</h2><strong>{formatCurrency(total)}</strong></div><div style={{overflowX:"auto"}}><table className={styles.table}><thead><tr><th>Date</th><th>Origine</th><th>Description</th><th>Montant</th></tr></thead><tbody>{rows.length?[...rows].reverse().map((r,i)=><tr key={`${r.entry_date}-${i}`}><td>{new Date(`${r.entry_date}T12:00:00`).toLocaleDateString("fr-FR")}</td><td>{r.entry_type}</td><td>{r.description||"—"}</td><td><strong>{formatCurrency(num(r.provider_amount))}</strong></td></tr>):<tr><td colSpan={4} className={styles.empty}>Aucune écriture.</td></tr>}</tbody></table></div></article></div>}
