import type { Concession, Provider, Vehicle } from "./types";

export const concessions: Concession[] = [
  {
    id: "c1",
    name: "Peugeot Car Avenue",
    city: "Yutz",
    address: "6 route de Thionville, 57970 Yutz",
    manager: "Julien Martin",
    email: "atelier.yutz@example.fr",
    activeProviders: 2,
    targetPerDay: 24,
    billedDayRate: 190,
  },
  {
    id: "c2",
    name: "Peugeot Autobernard",
    city: "Grenoble",
    address: "237 cours de la Libération, 38100 Grenoble",
    manager: "Benoît Laurent",
    email: "atelier.grenoble@example.fr",
    activeProviders: 1,
    targetPerDay: 20,
    billedDayRate: 180,
  },
  {
    id: "c3",
    name: "Stellantis Car Avenue",
    city: "Metz Borny",
    address: "Actipôle, 57070 Metz",
    manager: "Christophe Petit",
    email: "atelier.metz@example.fr",
    activeProviders: 2,
    targetPerDay: 24,
    billedDayRate: 190,
  },
];

export const providers: Provider[] = [
  {
    id: "p1",
    name: "Kevin Morel",
    initials: "KM",
    email: "kevin.morel@example.fr",
    phone: "06 00 00 00 01",
    concessionId: "c1",
    concessionName: "Peugeot Car Avenue · Yutz",
    paymentMode: "vehicle",
    rates: { day: 0, vo: 20, vn: 15, relavage: 10, tres_sale: 30, dailyDeduction: 0 },
    status: "active",
    vehiclesToday: 9,
    monthlyPay: 1840,
  },
  {
    id: "p2",
    name: "Maël Brikh",
    initials: "MB",
    email: "mael.brikh@example.fr",
    phone: "06 00 00 00 02",
    concessionId: "c2",
    concessionName: "Peugeot Autobernard · Grenoble",
    paymentMode: "day",
    rates: { day: 110, vo: 0, vn: 0, relavage: 0, tres_sale: 0, dailyDeduction: 0 },
    status: "active",
    vehiclesToday: 6,
    monthlyPay: 770,
  },
  {
    id: "p3",
    name: "Hamza Benali",
    initials: "HB",
    email: "hamza.benali@example.fr",
    phone: "06 00 00 00 03",
    concessionId: "c3",
    concessionName: "Stellantis Car Avenue · Metz Borny",
    paymentMode: "day",
    rates: { day: 120, vo: 0, vn: 0, relavage: 0, tres_sale: 0, dailyDeduction: 0 },
    status: "pending",
    vehiclesToday: 0,
    monthlyPay: 0,
  },
];

const today = new Date();
const iso = (hour: number, minute = 0) => {
  const date = new Date(today);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const initialVehicles: Vehicle[] = [
  {
    id: "v1",
    plate: "GH-284-LP",
    model: "Peugeot 3008",
    service: "Mécanique",
    billingType: "vo",
    status: "waiting",
    returnTime: "15:30",
    urgent: true,
    customerWaiting: true,
    concessionId: "c1",
    createdAt: iso(9, 12),
    billedAmount: 30,
  },
  {
    id: "v2",
    plate: "FT-916-KD",
    model: "Citroën C3",
    service: "Service rapide",
    billingType: "relavage",
    status: "waiting",
    returnTime: "16:00",
    urgent: false,
    customerWaiting: false,
    concessionId: "c1",
    createdAt: iso(9, 28),
    billedAmount: 20,
  },
  {
    id: "v3",
    plate: "GE-447-NR",
    model: "Peugeot 208",
    service: "Carrosserie",
    billingType: "tres_sale",
    status: "waiting",
    returnTime: "17:30",
    urgent: false,
    customerWaiting: false,
    concessionId: "c1",
    createdAt: iso(10, 6),
    billedAmount: 45,
  },
  {
    id: "v4",
    plate: "HJ-701-PT",
    model: "Opel Mokka",
    service: "Mécanique",
    billingType: "vo",
    status: "washing",
    returnTime: "14:45",
    urgent: true,
    customerWaiting: false,
    providerId: "p1",
    providerName: "Kevin Morel",
    concessionId: "c1",
    createdAt: iso(9, 35),
    startedAt: iso(10, 22),
    billedAmount: 30,
  },
  {
    id: "v5",
    plate: "GA-238-XM",
    model: "DS 7",
    service: "VO/VN",
    billingType: "vn",
    status: "washing",
    returnTime: "17:00",
    urgent: false,
    customerWaiting: false,
    providerId: "p1",
    providerName: "Kevin Morel",
    concessionId: "c1",
    createdAt: iso(9, 51),
    startedAt: iso(10, 43),
    billedAmount: 25,
  },
  {
    id: "v6",
    plate: "FW-113-ZA",
    model: "Peugeot 5008",
    service: "Mécanique",
    billingType: "vo",
    status: "done",
    returnTime: "12:00",
    urgent: false,
    customerWaiting: true,
    providerId: "p1",
    providerName: "Kevin Morel",
    concessionId: "c1",
    createdAt: iso(8, 48),
    startedAt: iso(9, 5),
    completedAt: iso(9, 47),
    billedAmount: 30,
  },
  {
    id: "v7",
    plate: "GX-902-VC",
    model: "Citroën C5 Aircross",
    service: "Carrosserie",
    billingType: "vo",
    status: "done",
    returnTime: "13:30",
    urgent: false,
    customerWaiting: false,
    providerId: "p1",
    providerName: "Kevin Morel",
    concessionId: "c1",
    createdAt: iso(8, 55),
    startedAt: iso(9, 52),
    completedAt: iso(10, 31),
    billedAmount: 30,
  },
  {
    id: "v8",
    plate: "GR-621-EB",
    model: "Peugeot 2008",
    service: "Service rapide",
    billingType: "relavage",
    status: "done",
    returnTime: "14:00",
    urgent: false,
    customerWaiting: false,
    providerId: "p1",
    providerName: "Kevin Morel",
    concessionId: "c1",
    createdAt: iso(9, 3),
    startedAt: iso(10, 35),
    completedAt: iso(11, 4),
    billedAmount: 20,
  },
];
